### ISSUE TITLE
TypeError: Cannot read property 'shift' of null

### ISSUE THREAD

**Issue by laamalif** [mlegenhausen/tor-auto-identity-changer#1]
FreeBSD + Node 0.12 + Tor 0.2.6.7

```
19 May 17:35:51 - Connected to localhost:9051
19 May 17:35:51 - Successful authenticated
19 May 17:35:51 - Requesting new identity each 10s
/tmp/tor-auto-identity-changer/main.js:12
        return callback(err, regex.exec(stdout).shift());
                                               ^
TypeError: Cannot read property 'shift' of null
    at /tmp/tor-auto-identity-changer/main.js:12:42
    at ChildProcess.exithandler (child_process.js:758:5)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
```

**Comment by mlegenhausen** [comment]
Can you reach http://checkip.dyndns.org/ from your system?
